In [1]:
#importing the required library 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#importing the csv file into pandas dataframe
logistic = pd.read_csv("User_Data.csv")

In [3]:
logistic.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
#lets spilit into X and Y
x = logistic.iloc[:,[2,3]].values
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [5]:
y = logistic.iloc[:,-1].values
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [6]:
#Import spliting the above x and y into traning and testing data
from sklearn.model_selection import train_test_split

In [7]:
#Spliting data into training (x and y) and testing where 80% for training and 20% testing
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)
x_old_train = x_train

In [8]:
print('The total size of data is ',len(logistic))
print('X traning data and X testing datas are ',len(x_train),'and', len(x_test))
print('Y target data and Y testing datas are ',len(y_train),'and', len(y_test))

The total size of data is  400
X traning data and X testing datas are  320 and 80
Y target data and Y testing datas are  320 and 80


In [9]:
#Lets import StandardScaler model from sklearn libray
from sklearn.preprocessing import StandardScaler
x_old_train

array([[    59,  88000],
       [    24,  19000],
       [    59,  29000],
       [    41,  59000],
       [    37,  57000],
       [    31,  71000],
       [    39, 134000],
       [    20,  49000],
       [    18,  44000],
       [    46,  22000],
       [    42,  70000],
       [    55,  39000],
       [    21,  68000],
       [    37,  77000],
       [    39, 122000],
       [    42,  65000],
       [    52,  90000],
       [    48,  30000],
       [    37,  79000],
       [    48,  29000],
       [    49,  39000],
       [    35,  77000],
       [    47,  20000],
       [    40,  65000],
       [    32,  18000],
       [    41,  72000],
       [    38,  51000],
       [    33, 149000],
       [    53,  72000],
       [    58,  23000],
       [    59,  76000],
       [    35, 147000],
       [    32, 135000],
       [    22,  55000],
       [    36, 144000],
       [    33,  60000],
       [    41,  30000],
       [    41,  71000],
       [    41,  52000],
       [    19,  26000],


In [10]:
#StandardScaler as Object
std_x = StandardScaler()

In [11]:
#StandardScaler is used to scale the numbers in range so easy to interprete max-min techniques 
x_train = std_x.fit_transform(x_train)

In [12]:
# X trained is now scaled downed in range
x_train

array([[ 2.03095586,  0.49148046],
       [-1.26853727, -1.46311043],
       [ 2.03095586, -1.17983639],
       [ 0.33407368, -0.33001426],
       [-0.04301125, -0.38666907],
       [-0.60863864,  0.00991459],
       [ 0.14553121,  1.79454106],
       [-1.64562219, -0.6132883 ],
       [-1.83416466, -0.75492532],
       [ 0.80542984, -1.37812822],
       [ 0.42834491, -0.01841281],
       [ 1.65387093, -0.89656234],
       [-1.55135096, -0.07506762],
       [-0.04301125,  0.17987902],
       [ 0.14553121,  1.45461221],
       [ 0.42834491, -0.16004983],
       [ 1.37105723,  0.54813527],
       [ 0.9939723 , -1.15150898],
       [-0.04301125,  0.23653383],
       [ 0.9939723 , -1.17983639],
       [ 1.08824353, -0.89656234],
       [-0.23155371,  0.17987902],
       [ 0.89970107, -1.43478302],
       [ 0.23980245, -0.16004983],
       [-0.51436741, -1.49143783],
       [ 0.33407368,  0.038242  ],
       [ 0.05125998, -0.55663349],
       [-0.42009618,  2.21945212],
       [ 1.46532846,

In [13]:
#Similar doing in testing data
x_test = std_x.fit_transform(x_test)

In [14]:
#Lets import the Logistic Regression module here to anlysis
from sklearn.linear_model import LogisticRegression

In [15]:
#Storing the logistic regression object in varible "Log"
Log = LogisticRegression()

In [16]:
#Finally Tranning the data
Log.fit(x_train,y_train)

LogisticRegression()

In [17]:
#Y prediction based on x are as below, so later do on other testing set as well after training
y_prediction = Log.predict(x_test)
y_prediction

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int64)

In [18]:
#Drwa Confusion Matrix
from sklearn.metrics import confusion_matrix

In [19]:
#Lets fit then y predicted vs y test data into CM
cm = confusion_matrix(y_prediction, y_test)
print(cm)

[[48  8]
 [ 6 18]]
